# Generated by Django 3.1.4 on 2020-12-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='message',
        ),
    ]
