# Generated by Django 3.1.4 on 2020-12-17 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_taskcomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomplete',
            name='status',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='todoapp.task'),
        ),
    ]
