# Generated by Django 3.1.4 on 2020-12-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_auto_20201218_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomplete',
            old_name='status',
            new_name='title',
        ),
    ]
