# Generated by Django 3.1.4 on 2020-12-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_auto_20201218_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomplete',
            old_name='title',
            new_name='mark',
        ),
    ]
