# Generated by Django 3.1.4 on 2020-12-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_auto_20201218_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomplete',
            name='mark',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoapp.task'),
        ),
    ]
