# Generated by Django 3.1.4 on 2020-12-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_delete_taskcomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
