# Generated by Django 3.1.4 on 2020-12-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0013_auto_20201221_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
